version: '2'
services:
  netsuiviapp2019-app:
    image: netsuiviapp2019
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://netsuiviapp2019-postgresql:5432/NetSuiviApp2019
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  netsuiviapp2019-postgresql:
    extends:
      file: postgresql.yml
      service: netsuiviapp2019-postgresql
